### ISSUE TITLE
Program crashes after a bit, when it gets undefined value even though there are exceptions to handle it

### ISSUE THREAD

**Issue by lacgondi** [HiImZsofi/mav-bot#14]
Here is the error:
TypeError: Cannot read properties of undefined (reading 'delay')
    at Query.<anonymous> (file:///mav-bot/main.js:48:18)
    at Query.<anonymous> (\mav-bot\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (\mav-bot\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (\mav-bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (\mav-bot\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (\mav-bot\node_modules\mysql\lib\protocol\sequences\Query.js:133:8)
    at Protocol._parsePacket (\mav-bot\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (\mav-bot\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (\mav-bot\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (\mav-bot\node_modules\mysql\lib\protocol\Protocol.js:38:16)

**Comment by lacgondi** [comment]
Fixed in #15
