### ISSUE TITLE
Bad field error: Unknown column 'undefined' in 'field list'

### ISSUE THREAD

**Issue by lacgondi** [HiImZsofi/mav-bot#9]
Uncaught Error Error: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'field list'
    at Sequence._packetToError (mav-bot\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (mav-bot\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (mav-bot\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at _parsePacket (mav-bot\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at write (mav-bot\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (mav-bot\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at <anonymous> (mav-bot\node_modules\mysql\lib\Connection.js:88:28)
    at <anonymous> (mav-bot\node_modules\mysql\lib\Connection.js:526:10)
    at emit (events:513:28)
    at addChunk (internal/streams/readable:315:12)
    at readableAddChunk (internal/streams/readable:289:9)
    at Readable.push (internal/streams/readable:228:10)
    at onStreamRead (internal/stream_base_commons:190:23)
    at callbackTrampoline (internal/async_hooks:130:17)
    --- TCPWRAP ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at Socket.connect (net:1052:7)
    at connect (net:212:17)
    at connect (mav-bot\node_modules\mysql\lib\Connection.js:76:13)
    at sendToDatabase (mav-bot\main.js:26:6)
    at <anonymous> (mav-bot\main.js:42:2)
    at listOnTimeout (internal/timers:559:17)
    at processTimers (internal/timers:502:7)
    --- Timeout ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at emitInitScript (internal/async_hooks:505:3)
    at initAsyncResource (internal/timers:162:5)
    at Timeout (internal/timers:196:3)
    at setInterval (timers:234:19)
    at <anonymous> (mav-bot\main.js:41:1)
    at run (internal/modules/esm/module_job:193:25)
    --- async function ---
    at <anonymous> (internal/modules/esm/loader:529:28)
    at processTicksAndRejections (internal/process/task_queues:96:5)
    --- Promise.then ---
    at import (internal/modules/esm/loader:529:10)
    at <anonymous> (internal/modules/run_main:58:28)
    at loadESM (internal/process/esm_loader:91:11)
    at processTicksAndRejections (internal/process/task_queues:96:5)
    --- async function ---
    at runMainESM (internal/modules/run_main:55:21)
    at executeUserEntryPoint (internal/modules/run_main:78:5)
    at <anonymous> (internal/main/run_main_module:17:47)

**Comment by lacgondi** [comment]
Fixed in #15
